---
name: POE-Filter-Hessian
version: v0.2.0
author:
  - 'William Travis Holton <cromulent2000_eisley@yahoo.de>'
abstract: |-
  Translate datastructures to and from Hessian for
  transmission via a POE ReadWrite wheel.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Contextual::Return: 0
  Exception::Class: 0
  Hessian::Client: '>=0.1.6'
  Moose: 0
  MooseX::Clone: 0
  Perl::Critic: 0
  Smart::Comments: 0
  Test::Class: 0
  Test::Deep: 0
  Test::More: 0
  Test::Perl::Critic: 0
  YAML: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  POE::Filter::Hessian:
    file: lib/POE/Filter/Hessian.pm
    version: v0.2.0
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
